### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by bczulauf** [bczulauf/inspect#13]
Just tried to download a report and got the following error:

Error: ENOENT, no such file or directory 'c:\inspect\public\uploads\Essential_Algorithms1422053344000.epub'
    at Object.fs.statSync (fs.js:696:18)
    at c:\inspect\server.js:506:18
    at c (c:\inspect\node_modules\firebase\lib\firebase-node.js:54:65)
    at c:\inspect\node_modules\firebase\lib\firebase-node.js:25:659
    at Ab (c:\inspect\node_modules\firebase\lib\firebase-node.js:24:165)
    at jf (c:\inspect\node_modules\firebase\lib\firebase-node.js:135:216)
    at kf (c:\inspect\node_modules\firebase\lib\firebase-node.js:134:864)
    at Ah.h.wd (c:\inspect\node_modules\firebase\lib\firebase-node.js:201:472)
    at Le.h.vd (c:\inspect\node_modules\firebase\lib\firebase-node.js:128:251)
    at we.vd (c:\inspect\node_modules\firebase\lib\firebase-node.js:120:364)

c:\inspect>

**Comment by rnchell** [comment]
This is because we don't push the files to github. So I have those locally but you won't

**Comment by bczulauf** [comment]
Makes sense. Closing.
